version: '3.7'

services: 
  mysql:
    container_name: payable_accounts_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - lyncas-net

  keycloak:
    container_name: payable_accounts_keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8081:8081
    command:
      - start-dev --http-port=8081 --hostname-url=http://keycloak.internal:8081
    volumes:
      - ../.docker/keycloak:/opt/keycloak/data/h2:rw
    networks:
      - lyncas-net

  app:
    container_name: payable_accounts
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - keycloak
    networks:
      - lyncas-net

networks:
  lyncas-net:
    driver: bridge
